# Generated by Django 5.0.6 on 2024-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=100)),
                ('catagpry', models.CharField(max_length=100)),
                ('subcatagory', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images/images')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='adress',
            field=models.TextField(max_length=500),
        ),
    ]
