# Generated by Django 5.0.7 on 2024-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_rename_catagpry_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placed_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('product_qty', models.IntegerField()),
                ('product_total_price', models.IntegerField()),
            ],
        ),
    ]
