# Generated by Django 5.0.7 on 2024-08-27 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_placed_orders_delevired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed_orders',
            name='orderplaced_date',
            field=models.DateField(default=datetime.date(2024, 8, 27)),
        ),
        migrations.AlterField(
            model_name='placed_orders',
            name='delivery_status',
            field=models.CharField(default='processing', max_length=50, null=True),
        ),
    ]
