# Generated by Django 5.0.7 on 2024-08-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Ph_Num', models.IntegerField()),
                ('Resume', models.FileField(upload_to='')),
                ('Date_of_joining', models.DateTimeField()),
                ('website', models.URLField(default='https:www.google.com')),
                ('Email', models.EmailField(default='abc@gmail.com', max_length=254)),
            ],
        ),
    ]
